# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('IMG', 'Image'), ('FILE', 'Fichier')], default='FILE', max_length=30)),
                ('file', models.FileField(null=True, upload_to=gallery.models.Attachment.get_upload_to)),
                ('image', models.ImageField(null=True, upload_to=gallery.models.Attachment.get_upload_to)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
    ]
