# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='article',
        ),
        migrations.RemoveField(
            model_name='image',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
