# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_remove_article_gallery'),
        ('gallery', '0002_auto_20170712_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
