# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170712_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='gallery',
            new_name='article',
        ),
    ]
