# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20170718_1338'),
        ('gallery', '0004_auto_20170712_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachement_type', models.CharField(choices=[('IMG', 'Image'), ('FILE', 'Fichier')], default='FILE', max_length=30)),
                ('file', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('image', models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
