# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20170718_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
