# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:02
from __future__ import unicode_literals

import article.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short', models.CharField(default='', max_length=1000)),
                ('file', models.FileField(null=True, upload_to=article.models.Article.get_upload_to)),
                ('category', models.CharField(choices=[('EXP', 'Expériences et bricolages'), ('PROJ', 'Projets'), ('BAZ', 'Bazar de Sivigik'), ('PROG', 'Programmation'), ('SITE', 'Vie du site')], default='SITE', max_length=30)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('is_beta', models.BooleanField(default=True)),
                ('slug', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
