# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('EXP', 'Expériences et bricolages'), ('PROJ', 'Projets'), ('BAZ', 'Bazar de Sivigik'), ('PROG', 'Programmation'), ('SITE', 'Vie du site')], default='SITE', max_length=2)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
