# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('EXP', 'Expériences et bricolages'), ('PROJ', 'Projets'), ('BAZ', 'Bazar de Sivigik'), ('PROG', 'Programmation'), ('SITE', 'Vie du site')], default='SITE', max_length=30),
        ),
    ]
