# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170705_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de publication'),
        ),
    ]
