# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20170705_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 5, 18, 19, 25, 309912, tzinfo=utc), verbose_name='Date de publication'),
        ),
    ]
