# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 08:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20170705_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_beta',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 8, 19, 16, 875934, tzinfo=utc), verbose_name='Date de publication'),
        ),
    ]
