# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20170707_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 8, 12, 15, 21, 573806, tzinfo=utc), verbose_name='Date de publication'),
        ),
    ]
