# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20170708_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 8, 12, 36, 39, 849892, tzinfo=utc), verbose_name='Date de publication'),
        ),
    ]
