# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20170708_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 8, 16, 58, 35, 692334, tzinfo=utc), verbose_name='Date de publication'),
        ),
    ]
