# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20170708_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
