# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170712_0912'),
        ('article', '0013_auto_20170711_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery'),
        ),
    ]
