# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_article_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='gallery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery'),
        ),
    ]
