# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20170712_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='gallery',
        ),
    ]
