# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_remove_article_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
