# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_articlefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlefile',
            name='article',
        ),
        migrations.DeleteModel(
            name='ArticleFile',
        ),
    ]
